Day 17

In [1]:
import numpy as np

# 지정된 값으로 배열 생성
a = np.array([1,2,3,4])
b = np.array([1,2,3.14,4])

print('a :', a) 
print('b : ', b) 

print('a.dtype : ',a.dtype) 
print('b.dtype : ',b.dtype) 

a : [1 2 3 4]
b :  [1.   2.   3.14 4.  ]
a.dtype :  int64
b.dtype :  float64


In [2]:
c = np.array([1,2,3,4], dtype=np.float32)

print('c : ',c)
print('c.dtype : ',c.dtype)

c :  [1. 2. 3. 4.]
c.dtype :  float32


In [3]:
# empty() 함수를 사용해서 배열 생성
empty=np.empty((4, 3))

print(empty)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [4]:
# zeros(), ones(), full() 함수를 사용해서 각각의 배열 생성
zero = np.zeros((2,3))
one= np.ones((2,3))
seven= np.full([2,3],7)

print("zero:",zero)
print("one:",one)
print("seven:",seven)

zero: [[0. 0. 0.]
 [0. 0. 0.]]
one: [[1. 1. 1.]
 [1. 1. 1.]]
seven: [[7 7 7]
 [7 7 7]]


In [5]:
arr = np.arange(10,  20)

print(arr)

[10 11 12 13 14 15 16 17 18 19]


In [6]:
arr = np.arange(10, 50, 5)

print(arr)

[10 15 20 25 30 35 40 45]


In [7]:
# 0이라는 시드값 설정
np.random.seed(0)

# 난수로 1차원 배열 생성  
a = np.random.rand(7)

print(a)

[0.5488135  0.71518937 0.60276338 0.54488318 0.4236548  0.64589411
 0.43758721]


In [8]:
# 난수로 다차원 배열 생성
a = np.random.rand(2,4)
b = np.random.rand(4,2,3)

print("a:\n", a)
print("b:\n", b)

a:
 [[0.891773   0.96366276 0.38344152 0.79172504]
 [0.52889492 0.56804456 0.92559664 0.07103606]]
b:
 [[[0.0871293  0.0202184  0.83261985]
  [0.77815675 0.87001215 0.97861834]]

 [[0.79915856 0.46147936 0.78052918]
  [0.11827443 0.63992102 0.14335329]]

 [[0.94466892 0.52184832 0.41466194]
  [0.26455561 0.77423369 0.45615033]]

 [[0.56843395 0.0187898  0.6176355 ]
  [0.61209572 0.616934   0.94374808]]]


Day 17-3. Numpy 배열 변형하기

In [9]:
# 지정된 값으로 배열 생성
a = np.array([1, 2, 3])

print(a) # 출력: [1 2 3]
print(a.dtype) # 출력: int64

# 배열의 dtype 변경
a_float = a.astype('float32')

print(a_float)
print(a_float.dtype)

[1 2 3]
int64
[1. 2. 3.]
float32


In [10]:
#순차적인 값으로 배열 생성
a = np.arange(12)

# 배열의 shape 변경
b = a.reshape(3, 4)

print("a:\n", a)
print("b:\n", b)

a:
 [ 0  1  2  3  4  5  6  7  8  9 10 11]
b:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [11]:
# 지정된 값으로 다차원 배열 생성
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

# 변경할 shape 설정
shape1 = (6, 2)
shape2 = (-1, 2)

# 배열의 shape 변경
output1 = np.reshape(arr, shape1)
output2 = np.reshape(arr, shape2)

print("reshape 1:\n",output1)
print("reshape 2:\n", output2)

reshape 1:
 [[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]
reshape 2:
 [[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]


In [12]:
# 지정된 값으로 다차원 배열 생성
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

# 다차원 배열을 1차원 배열로 변경
print(arr.flatten()) # 출력: [ 1  2  3  4  5  6  7  8  9 10 11 12]
print(arr.ravel()) # 출력: [ 1  2  3  4  5  6  7  8  9 10 11 12]

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [13]:
# 지정된 값으로 다차원 배열 생성
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

# 배열의 전치 연산
print(arr.T)

[[1 5]
 [2 6]
 [3 7]
 [4 8]]


In [14]:
# 난수로 배열 생성
a = np.random.rand(3, 4, 5)

# 첫 번째 축을 마지막 축으로 이동
result = np.moveaxis(a, 0, -1)

print(a.shape) # 출력: (3, 4, 5)
print(result.shape) # 출력: (4, 5, 3)

(3, 4, 5)
(4, 5, 3)


In [15]:
import numpy
# numpy 배열 생성
arr = numpy.array([1, 2, 3, 4, 5, 10, 15])

# numpy 배열을 list로 변경
x = arr.tolist()

print("Numpy Array :", arr) # 출력: Numpy Array : [ 1  2  3  4  5 10 15]
print("List :", x) # 출력: List : [1, 2, 3, 4, 5, 10, 15]


Numpy Array : [ 1  2  3  4  5 10 15]
List : [1, 2, 3, 4, 5, 10, 15]


In [16]:
# 다차원 numpy 배열 생성
arr = numpy.array([[1, 2], [3, 4]])

# 다차원 numpy 배열을 list로 변경
x = arr.tolist()

print("Numpy Array :\n", arr)
print("List :\n", x)

Numpy Array :
 [[1 2]
 [3 4]]
List :
 [[1, 2], [3, 4]]


Numpy2

In [17]:
# 1차원 배열 생성
arr = np.array([1, 2, 3, 4, 5])

print(arr[2])

3


In [18]:
# 다차원 배열 생성
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print(arr_2d[1, 2])

6


In [19]:
# 1차원 배열 생성
arr = np.array([1, 2, 3, 4, 5])

print(arr[1:4])

[2 3 4]


In [20]:
# 다차원 배열 생성
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print(arr_2d[1:, 1:3])

[[5 6]
 [8 9]]


In [21]:
# 1차원 배열 생성
arr = np.array([1, 2, 3, 4, 5])

# 배열에서 3보다 큰 값들만 선택
result = arr[arr > 3]

print(result)

[4 5]


In [22]:
# 1차원 배열 생성
a = np.array([11, 22, 33, 44, 55, 66, 77, 88, 99])

# 홀수번째 원소 indexing을 위한 인덱스 배열 생성
idx = np.array([0, 2, 4, 6, 8])

print(a[idx])

[11 33 55 77 99]


In [23]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

indexing1= a[:, [True, False, False, True]]

indexing2= a[[2, 0, 1], :]

print("indexing1:\n",indexing1)
print("indexing2:\n",indexing2)

indexing1:
 [[ 1  4]
 [ 5  8]
 [ 9 12]]
indexing2:
 [[ 9 10 11 12]
 [ 1  2  3  4]
 [ 5  6  7  8]]


Day 18-2. Numpy 배열의 병합

In [24]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6]])

result = np.concatenate((arr1, arr2), axis=0)
print(result)

[[1 2]
 [3 4]
 [5 6]]


In [25]:
import numpy as np

arr1 = np.array([1, 2])
arr2 = np.array([3, 4])

result = np.stack((arr1, arr2), axis=0)
print(result)

[[1 2]
 [3 4]]


In [26]:
a = np.array([[1, 2], [3, 4]]) # a.shape=(2, 2)
b = np.array([[5, 6], [7, 8]]) # b.shape=(2, 2)

print("concatenate:\n", np.concatenate((a, b), axis=0)) # shape=(4, 2)
print("stack:\n", np.stack((a, b), axis=0)) # shape=(2, 2, 2)

concatenate:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]
stack:
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [27]:
a = np.array([[1, 2], [3, 4]]) # a.shape=(2, 2)
b = np.array([[5, 6], [7, 8]]) # b.shape=(2, 2)

a_re = a.reshape((1, 2, 2))
b_re = b.reshape((1, 2, 2))

print("concatenate:\n",np.concatenate((a_re, b_re), axis=0))# shape=(2, 2, 2)
print("stack:\n",np.stack((a, b), axis=0)) # shape=(2, 2, 2)

concatenate:
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
stack:
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [28]:
x = np.array([1, 2, 3, 4, 5, 6])

print(np.split(x, 3))  # 출력: array([1, 2]), array([3, 4]), array([5, 6])


[array([1, 2]), array([3, 4]), array([5, 6])]


In [29]:
x = np.array([1, 2, 3, 4, 5, 6])

print(np.split(x, [2, 4]))

[array([1, 2]), array([3, 4]), array([5, 6])]


19. numpy 3

In [30]:
arr = np.array([1, 2, 3, 4, 5])

print(np.mean(arr))

3.0


In [31]:
arr = np.array([1, 2, 3, 4, 5])

print(np.var(arr))

2.0


In [32]:
arr = np.array([1, 2, 3, 4, 5])

print(np.std(arr))

1.4142135623730951


In [33]:
arr = np.array([1, 2, 3, 4, 5])

print(np.median(arr)) 

3.0


In [34]:
arr = np.array([1, 2, 3, 4, 5])

print(np.min(arr))  # 출력: 1
print(np.max(arr))

1
5


In [35]:
arr = np.array([1, 2, 3, 4, 5])

print(np.sum(arr))

15


In [36]:
arr = np.array([1, 2, 3, 4, 5])

print(np.percentile(arr, 50))

3.0


In [37]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

column_means = np.mean(arr, axis=0)

print(column_means)

[4. 5. 6.]


In [38]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

row_sums = np.sum(arr, axis=1)

print(row_sums)

[ 6 15 24]


Day 19-2. Numpy 배열과 이미지 데이터의 상관 관계

In [39]:
import cv2

In [41]:
# 이미지를 불러옴
image = cv2.imread("/Users/chae/Desktop/TaiLab_Severance_Hospital/000000.jpeg")

# (10, 10) 위치의 픽셀 값을 출력
print(image[10, 10])

# (10, 10) 위치의 픽셀 값의 type을 출력
print(type(image[10, 10]))

[14 14 14]
<class 'numpy.ndarray'>
